/**
 * UI tour spec — visits each curated route in the target stack, full-page
 * screenshots each, and surfaces dialog-open states.
 *
 * Authed routes rely on the storageState produced by the auth.setup.ts
 * project (which logs in as the seeded firstSuperuser). See
 * playwright.tour.config.ts for the project wiring.
 *
 * Generated by tools/ui_tour/ui_tour.sh — do not commit.
 */
import { test } from "@playwright/test"

const PUBLIC_ROUTES = [
  { path: "/login", name: "login" },
  { path: "/signup", name: "signup" },
  { path: "/recover-password", name: "recover_password" },
]

const AUTHED_ROUTES = [
  { path: "/", name: "dashboard" },
  { path: "/items", name: "items" },
  { path: "/time", name: "time" },
  { path: "/settings", name: "settings" },
  { path: "/admin", name: "admin" },
]

test.describe.serial("UI Tour — public routes", () => {
  // Public routes run with a clean browser context (no auth state).
  test.use({ storageState: { cookies: [], origins: [] } })

  for (const r of PUBLIC_ROUTES) {
    test(`tour ${r.name}`, async ({ page }) => {
      await page.goto(r.path)
      await page.waitForLoadState("networkidle", { timeout: 10_000 }).catch(() => {})
      await page.screenshot({
        path: `test-results/tour/${String(PUBLIC_ROUTES.indexOf(r)).padStart(2, "0")}_${r.name}.png`,
        fullPage: true,
      })
    })
  }
})

test.describe.serial("UI Tour — authed routes (as firstSuperuser)", () => {
  // Inherits storageState from the "chromium-authed" project, which depends
  // on the auth.setup project. No createUser / login flow needed here.

  for (const r of AUTHED_ROUTES) {
    test(`tour ${r.name}`, async ({ page }) => {
      await page.goto(r.path)
      await page.waitForLoadState("networkidle", { timeout: 10_000 }).catch(() => {})
      await page.screenshot({
        path: `test-results/tour/${String(10 + AUTHED_ROUTES.indexOf(r)).padStart(2, "0")}_${r.name}.png`,
        fullPage: true,
      })

      // If the route exposes a primary "Add X" button, open the dialog and snap it.
      const addButton = page.getByRole("button", { name: /^Add / })
      if (await addButton.count()) {
        await addButton.first().click().catch(() => {})
        await page.waitForTimeout(500)
        await page.screenshot({
          path: `test-results/tour/${String(10 + AUTHED_ROUTES.indexOf(r)).padStart(2, "0")}_${r.name}_dialog_open.png`,
          fullPage: true,
        })
      }
    })
  }
})
